spring.application.name=RequestManagement

#DataSource(webAppの丸写し)
#Postgresのドライバーの設定
spring.datasource.driver-class-name=org.postgresql.Driver

#データベースへの接続URLを設定
spring.datasource.url=jdbc:postgresql://localhost:5432/request

#データベース接続のためのユーザー名を設定
spring.datasource.username=postgres

#データベース接続のためのパスワードを設定
spring.datasource.password=postgrestest

#SQLスクリプトの初期化モードを設定
spring.sql.init.mode=always

#Log表示設定
logging.level.com.example.demo.mapper=DEBUG

#mybatisにresultmapを省略してもらう
mybatis.configuration.map-underscore-to-camel-case=true

#マッパー関係
mybatis.mapper-locations=classpath:/mapper/*.xml